service: todo-app-backend

provider:
  name: aws
  runtime: nodejs12.x

  region: eu-west-2

functions:
  tasksAWS:
    handler: handler.tasks
    events:
      - http:
         path: tasksURL
         method: get
         cors: true
      - http:
         path: tasksURL/{taskId}
         method: put
         cors: true
      - http:
         path: tasksURL
         method: post
         cors: true
      - http:
         path: tasksURL/{taskId}
         method: delete
         cors: true

